{
 "title": "DAG dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "dag_id",
    "label": "DAG ID",
    "query": {
     "query": "af_agg_dag_task_duration_count{airflow_id=\"$airflow_id\"}"
    }
   },
   { "name": "airflow_id", "label": "Airflow Instance Id", "query": { "query": "af_agg_dagbag_size" } }
  ]
 },
 "panels": [
  { "title": "DAG stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success DAG run duration",
   "type": "graph",
   "description": "Seconds taken for a DagRun to reach success state",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "af_agg_dagrun_duration_success{dag_id=\"$dag_id\"} * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "Failed DAG run duration",
   "type": "graph",
   "description": "Seconds taken for a DagRun to reach failed state",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "af_agg_dagrun_duration_failed{dag_id=\"$dag_id\"} * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "DAG run duration",
   "type": "graph",
   "description": "Sum of seconds taken to finish a tasks aggregated by DAG",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (dag_id, quantile) (af_agg_dag_task_duration{dag_id=\"$dag_id\"}) * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "DAG run dependency check time",
   "type": "graph",
   "description": "Seconds taken to check DAG dependencies",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "af_agg_dagrun_dependency_check{dag_id=\"$dag_id\"} * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "DAG run schedule delay",
   "type": "graph",
   "description": "Seconds of delay between the scheduled DagRun start date and the actual DagRun start date",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "af_agg_dagrun_schedule_delay{dag_id=\"$dag_id\"} * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  }
 ]
}
{
 "title": "Airflow Instance Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "airflow_id", "label": "Airflow Instance Id", "query": { "query": "af_agg_dagbag_size" } }
  ]
 },
 "panels": [
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scheduler heartbeat",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "af_agg_scheduler_heartbeat{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Dagbag size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "af_agg_dagbag_size{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "DAG processing total parse time",
   "type": "stat",
   "description": "Seconds taken to scan and import all DAG files once",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "af_agg_dag_processing_total_parse_time{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Dagbag import errors",
   "type": "stat",
   "description": "Number of errors from trying to parse DAG files",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "af_agg_dag_processing_import_errors{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Zombies killed",
   "type": "stat",
   "description": "Zombie tasks killed",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "af_agg_zombies_killed{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Total successful tasks",
   "type": "stat",
   "description": "Overall task instances successes",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "af_agg_ti_successes{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Operator success rate per minuite",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(af_agg_operator_successes{airflow_id=\"$airflow_id\"}[1m]) * 60",
     "legendFormat": "{{operator_name}}"
    }
   ]
  },
  {
   "title": "Operator failure rate per minute",
   "type": "graph",
   "description": "Total failures of given operator",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(af_agg_operator_failures{airflow_id=\"$airflow_id\"}[1m]) * 60",
     "legendFormat": "{{operator_name}}"
    }
   ]
  },
  {
   "title": "Total failed tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "af_agg_ti_failures{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Executor Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs started per minute",
     "type": "graph",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(af_agg_job_start{airflow_id=\"$airflow_id\"}[1m]) * 60",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Executor open slots",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "af_agg_executor_open_slots{airflow_id=\"$airflow_id\"}"
      }
     ]
    },
    {
     "title": "Executor queued tasks",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "af_agg_executor_queued_tasks{airflow_id=\"$airflow_id\"}"
      }
     ]
    },
    {
     "title": "Jobs ended per minute",
     "type": "graph",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(af_agg_job_end{airflow_id=\"$airflow_id\"}[1m]) * 60",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Executor running tasks",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "af_agg_executor_running_tasks{airflow_id=\"$airflow_id\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "DAG stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success DAG run duration",
     "type": "graph",
     "description": "Seconds taken for a DagRun to reach success state",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "af_agg_dagrun_duration_success{airflow_id=\"$airflow_id\"} * 1000",
       "legendFormat": "{{dag_id}} p{{quantile}}"
      }
     ]
    },
    {
     "title": "Failed DAG run duration",
     "type": "graph",
     "description": "Seconds taken for a DagRun to reach failed state",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "af_agg_dagrun_duration_failed{airflow_id=\"$airflow_id\"} * 1000",
       "legendFormat": "{{dag_id}} p{{quantile}}"
      }
     ]
    },
    {
     "title": "DAG run duration",
     "type": "graph",
     "description": "Sum of seconds taken to finish a tasks aggregated by DAG",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (dag_id, quantile) (af_agg_dag_task_duration{airflow_id=\"$airflow_id\"}) * 1000",
       "legendFormat": "{{dag_id}} p{{quantile}}"
      }
     ]
    },
    {
     "title": "DAG run dependency check time",
     "type": "graph",
     "description": "Seconds taken to check DAG dependencies",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "af_agg_dagrun_dependency_check{airflow_id=\"$airflow_id\"} * 1000",
       "legendFormat": "{{dag_id}} p{{quantile}}"
      }
     ]
    },
    {
     "title": "DAG run schedule delay",
     "type": "graph",
     "description": "Seconds of delay between the scheduled DagRun start date and the actual DagRun start date",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "af_agg_dagrun_schedule_delay{airflow_id=\"$airflow_id\"} * 1000",
       "legendFormat": "{{dag_id}} p{{quantile}}"
      }
     ]
    }
   ]
  }
 ]
}